# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 593ae1a04ae66e107e5a16043acdfbdbc38bf143c25ecbf21fc18f14a26d637c60d4ed5a1b4d291d78fca003f9cbc6cfc3d5e74a9d8afa899049812622e280ba

test:
  secret_key_base: e42c7e41189c1e5a4f8ca679d834504b5439c7892958fcc397abeca243ed39f7e58a66e77355782f944d9752a3638dbe45257dfd782c7b36edf38444053d13bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
